### PR TITLE
Update src/com/face4j/facebook/http/APICaller.java

### PR DESCRIPTION
**Pull request by alefq**
The file face4j.properties is not required. If it is not present, then proxy parameters are not needed.

### CODE REVIEW

**Comment by nischal** [comment]
Thanks! Makes sense.

**Comment by nischal** [comment]
You can pull the latest master branch and use face4j-1.7.1 which has this change in it.

**Comment by nischal** [comment]
You can also commit a similar change on https://github.com/nischal/insta4j

**Comment by alefq** [comment]
Cool! Thanks to you for sharing your project! 
This is my first contribution through a fork here on github, should I delete the branch as the site suggests?

**Comment by nischal** [comment]
yeah, you can :)

**Pull request merged**
